{"uuid": "5c1f95e8-e7de-4d05-8148-9e5743216c1c", "counter": 147, "stdout": "\u001b[0;31mThe full traceback is:\u001b[0m\r\n\u001b[0;31m  File \"/tmp/ansible_ansible.netcommon.cli_command_payload_50n_fq7b/ansible_ansible.netcommon.cli_command_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_command.py\", line 170, in main\u001b[0m\r\n\u001b[0;31m  File \"/tmp/ansible_ansible.netcommon.cli_command_payload_50n_fq7b/ansible_ansible.netcommon.cli_command_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\u001b[0m\r\n\u001b[0;31m    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\u001b[0m\r\n\u001b[0;31mfatal: [RegionA-PE02]: FAILED! => {\u001b[0m\r\n\u001b[0;31m    \"changed\": false,\u001b[0m\r\n\u001b[0;31m    \"invocation\": {\u001b[0m\r\n\u001b[0;31m        \"module_args\": {\u001b[0m\r\n\u001b[0;31m            \"answer\": null,\u001b[0m\r\n\u001b[0;31m            \"check_all\": false,\u001b[0m\r\n\u001b[0;31m            \"command\": \"show running-config\",\u001b[0m\r\n\u001b[0;31m            \"newline\": true,\u001b[0m\r\n\u001b[0;31m            \"prompt\": null,\u001b[0m\r\n\u001b[0;31m            \"sendonly\": false\u001b[0m\r\n\u001b[0;31m        }\u001b[0m\r\n\u001b[0;31m    },\u001b[0m\r\n\u001b[0;31m    \"msg\": \"[Errno None] Unable to connect to port 22 on 172.17.0.8\"\u001b[0m\r\n\u001b[0;31m}\u001b[0m", "start_line": 524, "end_line": 542, "runner_ident": "0ccf9392-afe6-4ac8-8f04-e8abb0293e95", "event": "runner_on_failed", "pid": 28, "created": "2021-11-07T11:27:32.621013", "parent_uuid": "0242ac11-001a-d762-d092-00000000000c", "event_data": {"playbook": "playbooks/get_config.yml", "playbook_uuid": "0627cab6-1f34-4f5f-998d-3edee47773f7", "play": "all", "play_uuid": "0242ac11-001a-d762-d092-000000000009", "play_pattern": "all", "task": "show command", "task_uuid": "0242ac11-001a-d762-d092-00000000000c", "task_action": "ansible.netcommon.cli_command", "task_args": "", "task_path": "/runner/project/playbooks/get_config.yml:17", "host": "RegionA-PE02", "remote_addr": "RegionA-PE02", "res": {"msg": "[Errno None] Unable to connect to port 22 on 172.17.0.8", "exception": "  File \"/tmp/ansible_ansible.netcommon.cli_command_payload_50n_fq7b/ansible_ansible.netcommon.cli_command_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_command.py\", line 170, in main\n  File \"/tmp/ansible_ansible.netcommon.cli_command_payload_50n_fq7b/ansible_ansible.netcommon.cli_command_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\n    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\n", "invocation": {"module_args": {"command": "show running-config", "newline": true, "sendonly": false, "check_all": false, "prompt": null, "answer": null}}, "_ansible_no_log": false, "changed": false}, "start": "2021-11-07T11:27:31.135263", "end": "2021-11-07T11:27:32.620793", "duration": 1.48553, "ignore_errors": null, "event_loop": null, "uuid": "5c1f95e8-e7de-4d05-8148-9e5743216c1c"}}