{"uuid": "3dd60993-b15d-434c-a169-88142f50efab", "counter": 147, "stdout": "\u001b[0;31mThe full traceback is:\u001b[0m\r\n\u001b[0;31m  File \"/tmp/ansible_ansible.netcommon.cli_command_payload_2pk1m7g_/ansible_ansible.netcommon.cli_command_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_command.py\", line 170, in main\u001b[0m\r\n\u001b[0;31m  File \"/tmp/ansible_ansible.netcommon.cli_command_payload_2pk1m7g_/ansible_ansible.netcommon.cli_command_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\u001b[0m\r\n\u001b[0;31m    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\u001b[0m\r\n\u001b[0;31mfatal: [RegionA-PE02]: FAILED! => {\u001b[0m\r\n\u001b[0;31m    \"changed\": false,\u001b[0m\r\n\u001b[0;31m    \"invocation\": {\u001b[0m\r\n\u001b[0;31m        \"module_args\": {\u001b[0m\r\n\u001b[0;31m            \"answer\": null,\u001b[0m\r\n\u001b[0;31m            \"check_all\": false,\u001b[0m\r\n\u001b[0;31m            \"command\": \"show running-config\",\u001b[0m\r\n\u001b[0;31m            \"newline\": true,\u001b[0m\r\n\u001b[0;31m            \"prompt\": null,\u001b[0m\r\n\u001b[0;31m            \"sendonly\": false\u001b[0m\r\n\u001b[0;31m        }\u001b[0m\r\n\u001b[0;31m    },\u001b[0m\r\n\u001b[0;31m    \"msg\": \"[Errno None] Unable to connect to port 22 on 172.17.0.8\"\u001b[0m\r\n\u001b[0;31m}\u001b[0m", "start_line": 524, "end_line": 542, "runner_ident": "43364685-db52-4ed2-8ef4-0095074908ac", "event": "runner_on_failed", "pid": 28, "created": "2021-11-07T11:29:07.515653", "parent_uuid": "0242ac11-001a-9b57-8aeb-00000000000c", "event_data": {"playbook": "playbooks/get_config.yml", "playbook_uuid": "f31565a0-1ac7-433d-bd4c-313215478c1b", "play": "all", "play_uuid": "0242ac11-001a-9b57-8aeb-000000000009", "play_pattern": "all", "task": "show command", "task_uuid": "0242ac11-001a-9b57-8aeb-00000000000c", "task_action": "ansible.netcommon.cli_command", "task_args": "", "task_path": "/runner/project/playbooks/get_config.yml:17", "host": "RegionA-PE02", "remote_addr": "RegionA-PE02", "res": {"msg": "[Errno None] Unable to connect to port 22 on 172.17.0.8", "exception": "  File \"/tmp/ansible_ansible.netcommon.cli_command_payload_2pk1m7g_/ansible_ansible.netcommon.cli_command_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_command.py\", line 170, in main\n  File \"/tmp/ansible_ansible.netcommon.cli_command_payload_2pk1m7g_/ansible_ansible.netcommon.cli_command_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\n    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\n", "invocation": {"module_args": {"command": "show running-config", "newline": true, "sendonly": false, "check_all": false, "prompt": null, "answer": null}}, "_ansible_no_log": false, "changed": false}, "start": "2021-11-07T11:29:06.123192", "end": "2021-11-07T11:29:07.515406", "duration": 1.392214, "ignore_errors": null, "event_loop": null, "uuid": "3dd60993-b15d-434c-a169-88142f50efab"}}